# Generated by Django 4.2.15 on 2024-08-16 19:35

from django.db import migrations, models
import person.models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='national_id',
            field=models.PositiveBigIntegerField(validators=[person.models.ValidateNationalID]),
        ),
    ]
